### ISSUE TITLE
Problème de dépendances PHP

### ISSUE THREAD

**Issue by ghost** [OTroccaz/ExtrHAL#1]
Bonjour l’équipe,

J'ai rencontré un problème sur une installation d'extrHAL, je n'arrivais pas à récupérer les exports, j'obtenais une bête erreur 404. Après avoir vérifier les logs, je constate qu'il manque des dépendances PHP.
Je pense que cela éviterai de nombreux problème si une liste des dépendances PHP nécessaires étaient placées dans un petit README.md.
Merci de votre compréhension
Cordialement,
Benjamin

**Comment by OTroccaz** [comment]
Bonjour,
Il n'y a pas de dépendance particulière : où se situait le problème ?
Cordialement,
Olivier

**Comment by ghost** [comment]
J'ai du ajouter php-mbstring

**Comment by OTroccaz** [comment]
J'ai différentes instances PHP sur plusieurs serveurs et l'extension y est par défaut. Par ailleurs, ExtrHAL a été installé par d'autres institutions et le problème ne s'est jamais posé.
Cordialement,
Olivier
