### ISSUE TITLE
"Nombre d'équipes" field does not show up with Chrome

### ISSUE THREAD

**Issue by boileaum** [OTroccaz/ExtrHAL#3]
First, thanks for this tool. My lab is preparing a ​HCERES evaluation campaign and ExtrHAL is a great help!

I report a bug of the web interface encountered under the current last version of Chrome (Version 97.0.4692.99 (Build officiel) (x86_64)) on MacOS 11.6.2, the field called "Nombre d'équipes" does not appear when "Numérotation/codification par équipe" is set to "oui" :

![image](https://user-images.githubusercontent.com/9973745/151539131-b7d4281d-0f5b-44cd-8523-7252ed0849ca.png)

No problem with Firefox.

**Comment by OTroccaz** [comment]
Thank you for informing me! I'll have a look at what the problem is...

**Comment by OTroccaz** [comment]
It's resolved.
Good afternoon!

**Comment by boileaum** [comment]
Thanks !
