### ISSUE TITLE
Communications orales (sans les posters)

### ISSUE THREAD

**Issue by larmarange** [OTroccaz/ExtrHAL#4]
Bonjour,

en regardant les options de ExtrHAL, il y a une options pour extraire uniquement les posters mais pas d'options pour extraire uniquement les communications orales (nationales/internationales, invitées ou non).

L'idée serait d'avoir l'équivalent de _Toutes les communications (sauf grand public)_ restreinte aux communications orales.

Dans un rapport d'activité, on nous demande souvent de séparer communications orales et poster.

En vous remerciant

**Comment by OTroccaz** [comment]
Bonjour,
Merci de cette suggestion : je l'ai insérée dans les options.
Bien cordialement,
Olivier

**Comment by larmarange** [comment]
Merci
